### ISSUE TITLE
Images saved from dc object cropped to ~1/4 size

### ISSUE THREAD

**Issue by earthbound19** [fogleman/Piet#2]
Hello,

I forked and tried adding image auto-save functionality to the source. This is my newest dev. revision at this writing:

https://github.com/earthbound19/Piet/blob/2c8b200290df42e89f2cfbb1d50a4aec9b0c94b5/main.py

The copied and saved bitmap seems to have 1/4 the resolution (it crops to the upper-left) when using the built-in e.g. `dc.AsBitmap` function.

This happens for me on a Mac. Refer to my pull request off my `doc` branch for the dependency setup I have.

Are you able to duplicate this problem? If so, any notions why this happens?

Thanks!

**Comment by fogleman** [comment]
Sounds like it might be a retina display issue.

**Comment by earthbound19** [comment]
Maybe so. It doesn't happen on a PC. If I see it again on a Mac I may investigate further, or maybe not :)
